apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

bases:
- ../../base/rbac
- ../../base/nfd-crds
- ../../base/master
- ../../base/worker-daemonset

resources:
- namespace.yaml

components:
- ../../components/worker-config
- ../../components/common

images:
- name: k8s.gcr.io/nfd/node-feature-discovery:v0.10.1
  newName: quay.io/mgiessing/node-feature-discovery
  newTag: v0.10.1
